import { stripToText } from '@cairn/shared';
import type { Contribution, PortfolioMetrics } from './metrics';

/**
 * Client-side portfolio generation (ADR-0013). Emits self-contained static output
 * with no external calls and no inline event handlers (CSP-safe). All user-supplied
 * free text is stripped to plain text before interpolation (SECURITY.md T15).
 */
export interface PortfolioInput {
  readonly name: string;
  readonly headline: string;
  readonly bio: string;
  readonly skills: readonly string[];
  readonly contributions: readonly Contribution[];
  readonly metrics: PortfolioMetrics;
  readonly links: readonly { label: string; url: string }[];
  readonly theme?: 'free-minimal' | 'premium-aurora';
}

function esc(s: string): string {
  return stripToText(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function safeUrl(u: string): string {
  try {
    const parsed = new URL(u);
    return parsed.protocol === 'https:' || parsed.protocol === 'mailto:'
      ? parsed.href
      : '#';
  } catch {
    return '#';
  }
}

export function toMarkdown(input: PortfolioInput): string {
  const m = input.metrics.headline;
  const lines = [
    `# ${stripToText(input.name)}`,
    '',
    `> ${stripToText(input.headline)}`,
    '',
    stripToText(input.bio),
    '',
    '## Open Source Metrics',
    '',
    `| Contribution | Consistency | Impact | Community |`,
    `| --- | --- | --- | --- |`,
    `| ${m.contribution} | ${m.consistency} | ${m.impact} | ${m.community} |`,
    '',
    '## Skills',
    '',
    input.skills.map((s) => `\`${stripToText(s)}\``).join(' '),
    '',
    '## Contributions',
    '',
    ...input.contributions.map(
      (c) =>
        `- [${stripToText(c.title)}](${safeUrl(c.url)}) — ${stripToText(c.repo)} (${c.mergedYear}-${String(
          c.mergedMonth,
        ).padStart(2, '0')})`,
    ),
  ];
  return lines.join('\n');
}

export function toHtml(input: PortfolioInput): string {
  const m = input.metrics.headline;
  const theme = input.theme ?? 'free-minimal';
  const rows = input.contributions
    .map(
      (c) =>
        `<li><a href="${safeUrl(c.url)}" rel="noopener noreferrer">${esc(c.title)}</a> — ${esc(
          c.repo,
        )} <span class="date">${c.mergedYear}-${String(c.mergedMonth).padStart(2, '0')}</span></li>`,
    )
    .join('');
  const skillTags = input.skills
    .map((s) => `<span class="tag">${esc(s)}</span>`)
    .join('');
  const links = input.links
    .map(
      (l) => `<a href="${safeUrl(l.url)}" rel="noopener noreferrer">${esc(l.label)}</a>`,
    )
    .join(' · ');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${esc(input.name)} — Open Source Portfolio</title>
<style>${themeCss(theme)}</style>
</head>
<body>
<main>
  <header>
    <h1>${esc(input.name)}</h1>
    <p class="headline">${esc(input.headline)}</p>
    <p class="links">${links}</p>
  </header>
  <p class="bio">${esc(input.bio)}</p>
  <section class="metrics">
    <div><span>${m.contribution}</span>Contribution</div>
    <div><span>${m.consistency}</span>Consistency</div>
    <div><span>${m.impact}</span>Impact</div>
    <div><span>${m.community}</span>Community</div>
  </section>
  <section><h2>Skills</h2><div class="tags">${skillTags}</div></section>
  <section><h2>Contributions</h2><ul class="contribs">${rows}</ul></section>
  <footer>Generated by Cairn</footer>
</main>
</body>
</html>`;
}

function themeCss(theme: 'free-minimal' | 'premium-aurora'): string {
  const base = `
:root{color-scheme:light dark;--fg:#1a1a1a;--bg:#fff;--muted:#666;--accent:#2563eb}
@media(prefers-color-scheme:dark){:root{--fg:#e8e8e8;--bg:#0e0e10;--muted:#9aa;--accent:#6ea8fe}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:16px/1.6 system-ui,sans-serif}
main{max-width:720px;margin:0 auto;padding:3rem 1.25rem}
h1{margin:0 0 .25rem}.headline{color:var(--muted);margin:0}
.links a,.contribs a{color:var(--accent)}
.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:.75rem;margin:2rem 0}
.metrics div{text-align:center;border:1px solid var(--muted);border-radius:10px;padding:.75rem}
.metrics span{display:block;font-size:1.6rem;font-weight:700}
.tags{display:flex;flex-wrap:wrap;gap:.4rem}.tag{border:1px solid var(--muted);border-radius:999px;padding:.15rem .6rem;font-size:.85rem}
.contribs{padding-left:1.1rem}.date{color:var(--muted);font-size:.85rem}
footer{margin-top:3rem;color:var(--muted);font-size:.85rem}`;
  if (theme === 'premium-aurora') {
    return (
      base +
      `body{background:linear-gradient(160deg,#0e0e10,#131a2b 60%,#1b1030);color:#e8ecff}
.metrics div{border-color:#6ea8fe55;background:#ffffff08}
h2{background:linear-gradient(90deg,#6ea8fe,#c58bff);-webkit-background-clip:text;background-clip:text;color:transparent}`
    );
  }
  return base;
}

export interface GeneratedPortfolio {
  readonly 'index.html': string;
  readonly 'portfolio.md': string;
}

export function generatePortfolio(input: PortfolioInput): GeneratedPortfolio {
  return { 'index.html': toHtml(input), 'portfolio.md': toMarkdown(input) };
}
